name: multi-job-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World!"
      - name: Print GoodBye
        run: echo "Done-Bye!"
  Second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World!"
      - name: Print GoodBye
        run: echo "Done-Bye!"
